markdown: kramdown
kramdown:
  smart_quotes: [ "apos", "apos", "quot", "quot" ]
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false
exclude: [ "Gemfile", "Gemfile.lock", "readme.md" ]
include: [ ".well-known" ]
name: "saibotsivad"
description: "Trying to be excellent in software and user interfaces."
url: "http://saibotsivad.com"
permalink: pretty
