markdown: kramdown
kramdown:
  smart_quotes: [ "apos", "apos", "quot", "quot" ]
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false
exclude: [ "Gemfile", "Gemfile.lock", "readme.md" ]
include: [ ".well-known" ]
name: "saibotsivad"
description: "I build software for businesses, and I would love to work with you on your next project!"
url: "http://saibotsivad.com"
permalink: pretty
